before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
dockers:
  - image_templates:
      - ghcr.io/STommydx/togolist:{{.Tag}}
      - ghcr.io/STommydx/togolist:v{{.Major}}
      - ghcr.io/STommydx/togolist:v{{.Major}}.{{.Minor}}
      - ghcr.io/STommydx/togolist:latest
    use: buildx
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
